"""Curated pool of real era-appropriate domains for search synthesis.

Every entry is a domain that actually existed in the era AND is likely to
have Wayback captures, so search results link to pages Dialback can really
serve. Keywords drive the offline keyword-scoring fallback; the LLM gets
the whole pool as its constraint.
"""

# (domain, title, description, keywords)
SITES = [
    ("www.geocities.com", "GeoCities",
     "Free home pages for everyone. Build your own neighborhood presence.",
     "homepages personal community free websites"),
    ("www.angelfire.com", "Angelfire",
     "Free web pages, graphics and tools for your personal site.",
     "homepages personal free web hosting"),
    ("members.tripod.com", "Tripod",
     "Free home pages and membership community.",
     "homepages community free"),
    ("www.altavista.digital.com", "AltaVista",
     "Search the web with the most powerful index online.",
     "search engine web index"),
    ("www.yahoo.com", "Yahoo!",
     "The web's best directory. Browse categories or search.",
     "directory search portal categories"),
    ("www.hotbot.com", "HotBot",
     "Wired's search engine of choice. Sweep the web.",
     "search engine wired"),
    ("www.lycos.com", "Lycos",
     "Catalog of the internet, search and entertainment.",
     "search engine catalog"),
    ("www.infoseek.com", "Infoseek",
     "Search the web, news, stocks and more.",
     "search portal news"),
    ("www.excite.com", "Excite",
     "Search, news, chat and free email.",
     "search portal chat email"),
    ("www.cnn.com", "CNN Interactive",
     "Breaking world news, updated throughout the day.",
     "news world breaking headlines"),
    ("www.nytimes.com", "The New York Times",
     "All the news that's fit to print, now on the web.",
     "news newspaper headlines"),
    ("www.bbc.co.uk", "BBC Online",
     "News, sport and programming from the BBC.",
     "news british television radio"),
    ("abcnews.go.com", "ABC News",
     "American broadcast news online.",
     "news television american"),
    ("www.slashdot.org", "Slashdot",
     "News for nerds. Stuff that matters.",
     "technology geek linux open source computers"),
    ("www.cnet.com", "CNET",
     "Computing and technology reviews, downloads and news.",
     "computers technology reviews downloads software"),
    ("www.download.com", "Download.com",
     "Shareware and freeware downloads, rated and reviewed.",
     "software downloads shareware freeware"),
    ("www.tucows.com", "TUCOWS",
     "The Ultimate Collection Of Winsock Software.",
     "software downloads winsock windows shareware"),
    ("www.windows95.com", "Windows95.com",
     "Tips, drivers and downloads for Windows 95.",
     "windows microsoft software drivers"),
    ("www.microsoft.com", "Microsoft",
     "Home of Windows, Office and Internet Explorer.",
     "windows microsoft software internet explorer"),
    ("www.apple.com", "Apple Computer",
     "Macintosh computers, QuickTime and more.",
     "macintosh apple mac computers quicktime"),
    ("www.ibm.com", "IBM",
     "Big Blue: hardware, software and services.",
     "computers hardware ibm business"),
    ("www.intel.com", "Intel",
     "Pentium processors inside.",
     "processors pentium chips hardware computers"),
    ("www.sun.com", "Sun Microsystems",
     "Java, workstations and the network is the computer.",
     "java solaris workstations unix"),
    ("www.netscape.com", "Netscape",
     "Navigator browser, Netcenter and directory.",
     "browser netscape navigator internet webmail"),
    ("home.netscape.com", "Netscape Netcenter",
     "Your start page for the net: search, shopping, channels.",
     "portal browser internet start page"),
    ("www.aol.com", "America Online",
     "You have mail. AOL keyword: internet.",
     "isp internet email community"),
    ("www.compuserve.com", "CompuServe",
     "The pioneering online service.",
     "isp online service email forums"),
    ("www.prodigy.com", "Prodigy Internet",
     "Online service for the whole family.",
     "isp online service family"),
    ("www.ebay.com", "eBay",
     "Person-to-person auctions. Bid on anything.",
     "auctions shopping collectibles bid"),
    ("www.amazon.com", "Amazon.com",
     "Earth's biggest bookstore. One million titles.",
     "shopping books bookstore retail"),
    ("www.cdnow.com", "CDnow",
     "Buy music CDs and cassettes online.",
     "music cds shopping store"),
    ("www.barnesandnoble.com", "Barnes & Noble",
     "Books, music and more from the bookseller.",
     "books shopping store"),
    ("www.imdb.com", "Internet Movie Database",
     "Everything about movies, TV and actors.",
     "movies film television database actors"),
    ("www.mp3.com", "MP3.com",
     "Downloadable music in the MP3 format.",
     "music mp3 audio download"),
    ("www.real.com", "RealNetworks",
     "RealAudio and RealVideo streaming media players.",
     "streaming audio video player realaudio"),
    ("www.macromedia.com", "Macromedia",
     "Shockwave, Flash and Director for the web.",
     "shockwave flash animation multimedia"),
    ("www.adobe.com", "Adobe Systems",
     "Acrobat, Photoshop and desktop publishing tools.",
     "acrobat photoshop pdf software design"),
    ("www.gamesdomain.com", "Games Domain",
     "Game reviews, cheats and downloads.",
     "games reviews cheats pc"),
    ("www.happypuppy.com", "Happy Puppy",
     "Game demos, hints and news.",
     "games demos hints console"),
    ("www.nintendo.com", "Nintendo",
     "Official home of Mario, Zelda and Nintendo 64.",
     "games console nintendo mario zelda"),
    ("www.sega.com", "Sega",
     "Sega Saturn and Genesis gaming.",
     "games console sega saturn genesis sonic"),
    ("www.sony.com", "Sony",
     "PlayStation, electronics and music.",
     "playstation games electronics console"),
    ("espnet.sportszone.com", "ESPN SportsZone",
     "Sports scores, news and analysis.",
     "sports scores basketball football baseball"),
    ("www.nba.com", "NBA.com",
     "Professional basketball official site.",
     "sports basketball scores"),
    ("www.weather.com", "The Weather Channel",
     "Forecasts and radar for your area.",
     "weather forecast radar maps"),
    ("www.mapquest.com", "MapQuest",
     "Interactive maps and driving directions.",
     "maps directions travel atlas"),
    ("www.travelocity.com", "Travelocity",
     "Book flights, hotels and rental cars.",
     "travel flights booking vacations"),
    ("www.expedia.com", "Expedia",
     "Microsoft travel planning and booking.",
     "travel flights booking maps"),
    ("www.quote.com", "Quote.Com",
     "Stock quotes and market data.",
     "stocks finance investing market"),
    ("www.motleyfool.com", "The Motley Fool",
     "Investing education with attitude.",
     "stocks finance investing humor"),
    ("www.hotmail.com", "Hotmail",
     "Free web-based email accessible anywhere.",
     "email free webmail"),
    ("www.dejanews.com", "Deja News",
     "Search and read Usenet newsgroups.",
     "usenet newsgroups discussion search"),
    ("faqs.org", "Internet FAQ Archives",
     "RFCs, FAQs and online documentation.",
     "documentation faqs rfc reference"),
    ("www.w3.org", "World Wide Web Consortium",
     "HTML specifications and web standards.",
     "html standards web specifications"),
    ("www.webcrawler.com", "WebCrawler",
     "Fast, simple web searching.",
     "search engine web"),
    ("www.metacrawler.com", "MetaCrawler",
     "Searches multiple search engines at once.",
     "search meta engine metasearch"),
    ("www.askjeeves.com", "Ask Jeeves",
     "Ask questions in plain English.",
     "search questions answers natural language"),
    ("www.xfiles.com", "The X-Files",
     "Official site for the truth being out there.",
     "television scifi xfiles fox mulder"),
    ("www.starwars.com", "Star Wars",
     "Official Star Wars trilogy and prequel news.",
     "movies scifi starwars lucasfilm"),
    ("www.startrek.com", "Star Trek: Continuum",
     "Official Star Trek universe site.",
     "television scifi startrek paramount"),
    ("www.disney.com", "Disney.com",
     "Family entertainment from the mouse.",
     "family entertainment kids movies"),
    ("www.paramount.com", "Paramount Pictures",
     "Movies and television from Paramount.",
     "movies television studio hollywood"),
]
